language: d

sudo: required
dist: trusty

d:
  - dmd-2.069.2
  - dmd-2.068.2
  - dmd-2.067.1
  - dmd-2.066.1
  - ldc-1.0.0
  - ldc-0.16.1
  - ldc-0.15.1
  - gdc

before_install:
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install sqlite; fi"

os:
 - linux
 - osx

script:
  - dub build --config=SQLite
  - cd hdtest && dub --config=SQLite

addons:
  apt:
    packages: [ libsqlite3-dev ]

matrix:
  allow_failures:
    - os: osx
      d: ldc-1.0.0
    - os: osx
      d: ldc-0.16.1
    - os: osx
      d: ldc-0.15.1
    - d: gdc
